parser: babel-eslint
extends:
  - eslint:recommended
  - google
rules:
  indent: [error, 2]
  max-len: [error, 120]
  no-new: warn
  quotes: [error, single, {"avoidEscape": true}]
  no-var: error
  curly: error
  no-floating-decimal: error
  no-unused-vars:
    - error
    - args: all

  # TODO: Enable once we use jsdoc
  require-jsdoc: off
  valid-jsdoc: off

  no-console: off
